### ISSUE TITLE
Certain Colors not Working.

### ISSUE THREAD

**Issue by Dourwlo** [GabiRP/KillMessage#2]
- Within the plugin, I have tested out the colors that were from the official SCP SL Wiki. 

<html>
<body>

pink | #FF96DE | Server groups
-- | -- | --
red | #C50000 | Server groups
brown | #944710 | Server groups
silver | #A0A0A0 | Server groups
light_green | #32CD32 | Server groups
crimson | #DC143C | Server groups
cyan | #00B7EB | Server groups
aqua | #00FFFF | Server groups
deep_pink | #FF1493 | Server groups
tomato | #FF6448 | Server groups
yellow | #FAFF86 | Server groups
magenta | #FF0090 | Server groups
blue_green | #4DFFB8 | Server groups
orange | #FF9966 | Server groups
lime | #BFFF00 | Server groups
green | #228B22 | Server groups
emerald | #50C878 | Server groups
carmine | #960018 | Server groups
nickel | #727472 | Server groups
mint | #98FB98 | Server groups
army_green | #4B5320 | Server groups
pumpkin | #EE7600 | Server groups

</body>
</html>

Within my testing, there where only five colors that worked for the plug-in which includes:
<html>
<body>

pink | #FF96DE | Server groups
-- | -- | --
red | #C50000 | Server groups
yellow | #FAFF86 | Server groups
orange | #FF9966 | Server groups
green | #228B22 | Server groups
White| #FFFFFF | Server Groups

</body>
</html>

**Comment by GabiRP** [comment]
For broadcast, you'll need to use colors from [Unity Rich Text](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html)

For hints, i've tested, and only
red, yellow, orange, black, blue, green, grey, lightblue, purple
work. 
So i'll make a note about this in the README. Thanks!

**Comment by GabiRP** [comment]
And someone just told me that you can use Hex Colors, so i'll make an update to the plugin adding hex support without needing to add them to the config
