### ISSUE TITLE
 message_duration not working correctly

### ISSUE THREAD

**Issue by Playeroth** [GabiRP/KillMessage#3]
if you set any number above 10s he will still stays at 1s. if you set below 5s he dissapear way faster than 1s.
they are not working correctly.

**Comment by GabiRP** [comment]
Can't reproduce.
If you have any other plugin that uses hints or broadcast, disable it and try again.

**Comment by Playeroth** [comment]
wierd, just tested with broadcasts and they work fine but hints doesnt. 
Plugins im using that modifies hints:
ExiledUtils-Remake https://github.com/xNexus-ACS/ExiledUtils/releases/tag/3.0.3
ShowZombieCount https://github.com/BuildBoy12/ShowZombieCount
and XPSystem https://github.com/BruteForceMaestro/Progression
(screenshot for full plugins)
and i disabled Progression(XPSystem) for testing and the hints were still bugged, disabled both ShowZ and ExiledU and still bugged

my config 

![Capture](https://user-images.githubusercontent.com/50618172/163491985-fd973c12-c169-4c34-b703-0682d359629b.PNG)


![Capture](https://user-images.githubusercontent.com/50618172/163491747-a12848dd-f490-45ea-b684-032274973c93.PNG)

**Comment by GabiRP** [comment]
Is use_broadcast set to false? If yes, then try disabling RespawnTimer to see if it works.

**Comment by Playeroth** [comment]
i disabled RespawnTimer completely and it works now with hints, weirdly that other plugins that uses hints midgame works fine, so its something with the plugin

**Comment by GabiRP** [comment]
Thing is, RespawnTimer only uses hints on spectator afaik, for that exact reason I made the ``use_broadcast`` config. So if you want to see the messages, set that config to true and use broadcasts.

**Comment by Playeroth** [comment]
just realized that when you die the custom message(KillMessage) will appear and so the RespawnTimer, they dont work because both are appearing on the same moment and that is what i wasnt undersdanting because i forgot KillMessage uses spectator event too, my bad.
